config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('services.urls'))
]
urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

services/urls.py
from django.urls import path
from .import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'services'

urlpatterns = [
    path("", views.index, name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),

    ## web
    path('scantext/', views.scan_text, name="scan_text"),
    path('translate/', views.translateText, name="translateText"),
    path('texttospeech/', views.texttospeech, name="texttospeech"),

    ## apis
    path('api/texttospeech/', views.text_to_speech_api, name="texttospeech_api"),

    path('api/scantext/', views.scan_text_api, name="scan_text_api"),
    path('api/translate/', views.translateText_api, name="translateText_api"),

    ## epxport
    path('exportScanText/', views.exportScanText, name="exportScanText"),
    path('exportTranslateText/', views.exportTranslateText, name="exportTranslateText"),
]

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <img src="{% static 'images/logo.png' %}" class="img-fluid" alt="DjangoX logo"/>
  <p class="lead">A Django starter project with batteries.</p>
</div>
{% endblock content %}

templates/pages/scan_text.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Scan Text
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="container   d-flex flex-column shadow-lg bg-white">
        <br>
        <br>
        <br>



        <div class="row justify-content-center align-items-center   mt-4">
            <div class="col-md-5">
                <img src="{% static 'images/scan_text.png' %}" alt=""
                    style="width: 100%; height: 400px; object-fit: contain;">
            </div>
            <div class="col-md-7">
                <div class="container   d-flex flex-column">
                    <h2>
                        Upload your image below
                    </h2>
                    <hr>
                    <br>
                    <form class="forms-sample dropzone" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- <div class="form-group dropzone">
                            {{ form }}
                        </div>
                        <br>
 -->

                        <div class=" image-form-section">
                            <div>
                                <p id="imgStatus" class="text-danger display-4"></p>
                            </div>
                            <br>
                            <div class="form-group dropzone">
                                {{ form | crispy }}
                            </div>
                            <br>
                            <!-- <div class="position-relative">
                                <div class="img-display">
                                </div>
                                <p class="position-absolute" style="bottom: 0; left: 0; z-index: 12;">
                                    {{ form.image }}</p>
                            </div> -->
                        </div>
                        

                        <input type="submit" class="btn btn-dark btn-lg btn-block mt-3" value="Scan Text">
                    </form>
                </div>
            </div>

            <div class="col-md-12">

                <br>
                <br>

                {% if docText %}
                
                <div class="row pb-4">
                    <div class="col-md-6">
                        <img width="100%" src="{{ myimageurl }}" alt="img not found" srcset="">
                    </div>
                    <div class="col-md-6  align-items-left">
                        <form method="GET" action="{% url 'services:exportScanText' %}" style="width: 90%;">
                            <div>
                                <textarea name="text" id="txtArea" rows="8" style="width: 100%;">{{ docText }}</textarea>
                            </div>
                            <div class="row text-left align-items-left d-flex">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="ex_type" id="exampleRadios1" value="word" checked>
                                    <label class="form-check-label" for="exampleRadios1">
                                      Word .docx
                                    </label>
                                  </div>
                                  <div class="form-check">
                                    <input class="form-check-input" type="radio" name="ex_type" id="exampleRadios2" value="pdf">
                                    <label class="form-check-label" for="exampleRadios2">
                                      Pdf .pdf
                                    </label>
                                  </div>
                            </div>
                            <div class="pb-2 row">
                                <div class="col-md-12 d-flex flex-row">
                                    <input type="submit" class="btn btn-success btn-md " value="Export">
                                    <p class="m-3"></p>
                                    <!-- <input type="submit" class="btn btn-success btn-md " value="Export .docx"> -->
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                {% endif %}
            </div>
        </div>
    </div>

</div>

<script>

    let btn = document.getElementById('id_image');
    let status = document.getElementById('imgStatus');

    btn.addEventListener('change', (e) => {
        status.innerHTML = "File Picked ☺️";
        });



</script>


{% endblock %}

templates/pages/translate_text.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Scan Text
{% endblock %}

{% block content %}
<div class="container bg-white shadow-lg   d-flex flex-column">
    <br>
    <br>
    <br>

    <div class="row justify-content-center    mt-4">
        <div class="col-md-5">
            <img src="{% static 'images/translate_text.png' %}" alt="" width="100%">
        </div>
        <div class="col-md-7">
            <h2>
                Translate your text below
            </h2>
            <hr>
            <br>
            <div class="container   d-flex flex-column">
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    {% csrf_token %}


                    <div class="form-group">
                        {{ form | crispy }}
                    </div>
                                
                    <input type="submit" class="btn btn-dark btn-lg mt-5" value="Translate">
                </form>
            </div>
            <br>
            {% if translation != "" %}

            <div class="row pb-4">
                <div class="col-md-12  align-items-left">
                    <form method="GET" action="{% url 'services:exportTranslateText' %}" style="width: 90%;">
                        <div>
                            <textarea name="text" id="txtArea" rows="8" style="width: 100%;">{{ translation }}</textarea>
                        </div>
                        <div class="row text-left align-items-left d-flex">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="ex_type" id="exampleRadios1" value="word" checked>
                                <label class="form-check-label" for="exampleRadios1">
                                  Word .docx
                                </label>
                              </div>
                              <div class="form-check">
                                <input class="form-check-input" type="radio" name="ex_type" id="exampleRadios2" value="pdf">
                                <label class="form-check-label" for="exampleRadios2">
                                  Pdf .pdf
                                </label>
                              </div>
                        </div>
                        <div class="pb-2 row">
                            <div class="col-md-12 d-flex flex-row">
                                <input type="submit" class="btn btn-success btn-md " value="Export">
                                <p class="m-3"></p>
                                <!-- <input type="submit" class="btn btn-success btn-md " value="Export .docx"> -->
                            </div>
                        </div>
                    </form>
                </div>
            </div>

           <!--  <textarea id="" rows="4" style="width: 100%;">
                {{ translation }}
                </textarea> -->
            {% endif %}
            <br>
        </div>

        <br>
        <br>
    </div>

    {% endblock %}

templates/pages/tts.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Scan Text
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="container text-center  shadow-lg bg-white">
        <br>
        <br>



        <div class="row justify-content-center align-items-center text-center mt-4">
            <div class="col-md-5">
                <img src="{% static 'images/text-to-speech.jpg' %}" alt=""
                    style="width: 100%; height: 400px; object-fit: contain;">
            </div>
            <div class="col-md-7">
                <div class="container text-center d-flex flex-column">
                    <h2>
                        Convert your text to Audio
                    </h2>
                    <hr>
                    <br>
                    <form class="forms-sample dropzone" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group dropzone">
                            {{ form | crispy }}
                        </div>
                        <input type="submit" class="btn btn-dark btn-lg btn-block mt-3" value="Convert">
                    </form>
                </div>

                <div class="mt-5">
                    {% if filename %}
                    <audio src="{{filename}}" autoplay controls></audio>
                    {% endif %}
                </div>
                <br>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">

        </div>
    </div>

</div>



{% endblock %}