config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('services.urls'))
]
urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

services/urls.py
from django.urls import path
from .import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'services'

urlpatterns = [
    path("", views.index, name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),

    ## web
    path('scantext/', views.scan_text, name="scan_text"),
    path('translate/', views.translateText, name="translateText"),
    path('texttospeech/', views.texttospeech, name="texttospeech"),

    ## apis
    path('api/texttospeech/', views.text_to_speech_api, name="texttospeech_api"),

    path('api/scantext/', views.scan_text_api, name="scan_text_api"),
    path('api/translate/', views.translateText_api, name="translateText_api"),

    ## epxport
    path('exportScanText/', views.exportScanText, name="exportScanText"),
    path('exportTranslateText/', views.exportTranslateText, name="exportTranslateText"),
]

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} HOME PAGE {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>

    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}


    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
    <script type="text/javascript" defer src="{% static 'js/base.js' %}"></script>

    <script>
        $('#myModal').on('shown.bs.modal', function () {
            $('#myInput').trigger('focus')
        })
    </script>
</body>

</html>

templates/index.html
{% extends '_base.html' %} {% load static %} {% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <h2 class="display-2 mt-3">
                <b>
                    Scan, Translate, Convert Text to Speech
                </b>
            </h2>
            <br><br>
            <h4>
                We give you the best way and convenient way to scan, translate and convert your text
                to audio the easiest way.
            </h4>
            <br>
            <br>
            <div>
                <a href="#getstarted" class="btn btn-rounded btn-dark">Get Started</a>
            </div>

        </div>
        <div class="col-md-7">
            <img src="{% static 'images/scan_document.png' %}" alt="" width="100%">
        </div>
    </div>
    <br>
</div>

<div class="container-fluid bg-white">
    <div class="row">
        <div class="col-md-5">
            <img src="{% static 'images/scan_text.png' %}" alt=""
                style="width: 100%; height: 400px; object-fit: contain;">
        </div>
        <div class="col-md-7 p-4">
            <h2>Scan Text</h2>
            <h4>
                Scan your handwritten document to digital form the easiest way.
                upload your file, or take a picture and upload to scan text from
                your document.
            </h4>
            <div class="pt-4">
                <a href="{% url 'services:scan_text' %}" class="btn btn-lg btn-dark btn-rounded"> Try it Now!</a>
            </div>
        </div>
    </div>
</div>




<div class="container">
    <div class="row p-3">
        <div class="col-md-7 p-4">
            <h2>Translate Text</h2>
            <h4>
                Wondering how you can communicate with someone who doesn't understand your language?
                Translate your English text to different languages the easiest way.
            </h4>
            <div class="pt-4">
                <a href="{% url 'services:translateText' %}" class="btn btn-lg btn-dark btn-rounded"> Try it Now!</a>
            </div>
        </div>
        <div class="col-md-5">
            <img src="{% static 'images/translate_text.png' %}" alt="" width="100%">
        </div>
    </div>
</div>

<div class="container-fluid bg-white">
    <div class="row p-3">
        <div class="col-md-5">
            <img src="{% static 'images/text-to-speech.jpg' %}" alt=""
                style="width: 100%; height: 400px; object-fit: contain;">
        </div>
        <div class="col-md-7 p-4">
            <h2>Text to Speech</h2>
            <h4>
                Do you feel lazy to read something? Let us read your notes, articles, and many more text for you.
            </h4>
            <div class="pt-4">
                <a href="{% url 'services:texttospeech' %}" class="btn btn-lg btn-dark btn-rounded"> Try it Now!</a>
            </div>
        </div>

    </div>
</div>



<div class="container  shadow-sm p-4" style="height: 750px;" id="getstarted">
    <div class="row justify-content-center align-items-center text-center mt-4">
        <div class="col-md-8">
            <h5 class="display-5">
                What do you want to do?
            </h5>
        </div>
    </div>
    <br>
    <br>

    <div class="row justify-content-center align-items-center text-center mt-4">
        <div class="col-md-4 text-center mb-4">
            <a class="card shadow-lg text-center text-decoration-none" href="{% url 'services:scan_text' %}">
                <img class="card-img-top cimage text-center" src="{% static 'images/convert.png' %}"
                    alt="Card image cap">
                <div class="card-body">
                    <h3 class="card-title">
                        Scan Text
                    </h3>
                    <hr>
                    <p class="card-text">
                        Convert Handwritten text into digital form
                    </p>
                </div>
            </a>
        </div>
        <div class="col-md-4 text-center mb-4">
            <a class="card shadow-lg text-center text-decoration-none" href="{% url 'services:translateText' %}">
                <img class="card-img-top cimage text-center" src="{% static 'images/translate.png' %}"
                    alt="Card image cap">
                <div class="card-body">
                    <h3 class="card-title">
                        Translate Text
                    </h3>
                    <hr>
                    <p class="card-text">
                        Copy and paste text to Translate
                    </p>
                </div>
            </a>
        </div>
        <div class="col-md-4 text-center mb-4">
            <a class="card shadow-lg text-center text-decoration-none" href="{% url 'services:texttospeech' %}">
                <img class="card-img-top cimage text-center" src="{% static 'images/text-to-speech.png' %}"
                    alt="Card image cap">
                <div class="card-body">
                    <h3 class="card-title">
                        Text To Speech
                    </h3>
                    <hr>
                    <p class="card-text">
                        convert your text to audio
                    </p>
                </div>
            </a>
        </div>
        <!-- <div class="col-md-4 text-center mb-4">
            <a class="card shadow-lg text-center text-decoration-none" href="#">
                <img class="card-img-top cimage text-center" src="{% static 'images/history.png' %}"
                    alt="Card image cap">
                <div class="card-body">
                    <h3 class="card-title">
                        history
                    </h3>
                    <hr>
                    <p class="card-text">
                        Check your History
                    </p>
                </div>
            </a>
        </div> -->
    </div>

</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
       PRIME SCANNER
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <!--<a class="nav-link active" aria-current="page" href="/">Home</a>
          <a class="nav-link" href="/">About</a>
          <a class="nav-link" >scan text</a>
           <a class="nav-link" href="#">Pricing</a>
          <a class="nav-link disabled">Disabled</a> -->
        </div>
      </div>
    </div>
  </nav>

templates/pdf_template.html
<!-- <!DOCTYPE html>
<html lang="en"> -->
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/mdb.min.css">

<!--     <style>
        @page {
            size: 80mm 120mm;
        }
    </style> -->
</head>

<body>
    <div class="container">
        <h4>
            {{ text }}
        </h4>
    </div>
</body>

</html>

templates/scaned-text.html
{% extends '_base.html' %} 
{% load crispy_forms_tags %}

{% block title %}
REQUEST HAIR DO
{% endblock %}

{% block content %}
<div class="container text-center d-flex flex-column">
    <br>
    <br>
    <br>
 


     <div class="row">
         <div class="col-md-12">
            <div class="container text-center d-flex flex-column">
                <h1>
                    The value could be: <span>{{ prediction }}</span>
                </h1>
            </div>
         </div>
         <br>
         <p>
            Loss: <span>{{ loss }}</span> <br>
            Accuracy: <span> {{ accuracy }} </span>
         </p>
     </div>
</div>
{% endblock %}